### ISSUE TITLE
ModuleNotFoundError: No module named 'pandas' when attempting remora model list_pretrained

### ISSUE THREAD

**Issue by billytcl** [nanoporetech/remora#1]
There seems to be a missing package requirement during install. It's fixed when I run conda install pandas afterward.

```
billylau@suzuki:~$ conda create -n remora python=3.8
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /home/billylau/.conda/envs/remora:

The following NEW packages will be INSTALLED:

    _libgcc_mutex:    0.1-main                
    ca-certificates:  2021.10.26-h06a4308_2   
    certifi:          2021.10.8-py38h06a4308_0
    ld_impl_linux-64: 2.35.1-h7274673_9       
    libffi:           3.3-he6710b0_2          
    libgcc-ng:        9.1.0-hdf63c60_0        
    libstdcxx-ng:     9.1.0-hdf63c60_0        
    ncurses:          6.3-h7f8727e_2          
    openssl:          1.1.1l-h7f8727e_0       
    pip:              21.2.4-py38h06a4308_0   
    python:           3.8.12-h12debd9_0       
    readline:         8.1-h27cfd23_0          
    setuptools:       58.0.4-py38h06a4308_0   
    sqlite:           3.36.0-hc218d9a_0       
    tk:               8.6.11-h1ccaba5_0       
    wheel:            0.37.0-pyhd3eb1b0_1     
    xz:               5.2.5-h7b6447c_0        
    zlib:             1.2.11-h7b6447c_3       

Proceed ([y]/n)? y

#
# To activate this environment, use:
# > source activate remora
#
# To deactivate an active environment, use:
# > source deactivate
#

billylau@suzuki:~$ source activate remora
(remora) billylau@suzuki:~$ remora model list_pretrained
remora: command not found
(remora) billylau@suzuki:~$ pip install ont-remora
Collecting ont-remora
  Downloading ont-remora-0.1.1.tar.gz (15.0 MB)
     |████████████████████████████████| 15.0 MB 11.6 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
Collecting numpy
  Downloading numpy-1.21.4-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.7 MB)
     |████████████████████████████████| 15.7 MB 158.2 MB/s 
Collecting tqdm
  Using cached tqdm-4.62.3-py2.py3-none-any.whl (76 kB)
Collecting onnxruntime>=1.7
  Downloading onnxruntime-1.9.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.8 MB)
     |████████████████████████████████| 4.8 MB 48.1 MB/s 
Collecting thop
  Downloading thop-0.0.31.post2005241907-py3-none-any.whl (8.7 kB)
Collecting onnx
  Downloading onnx-1.10.2-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (12.7 MB)
     |████████████████████████████████| 12.7 MB 30.9 MB/s 
Collecting torch
  Downloading torch-1.10.0-cp38-cp38-manylinux1_x86_64.whl (881.9 MB)
     |████████████████████████████████| 881.9 MB 5.5 kB/s 
Collecting scikit-learn
  Using cached scikit_learn-1.0.1-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (25.9 MB)
Collecting tabulate
  Downloading tabulate-0.8.9-py3-none-any.whl (25 kB)
Collecting protobuf
  Downloading protobuf-3.19.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.1 MB)
     |████████████████████████████████| 1.1 MB 134.1 MB/s 
Collecting flatbuffers
  Downloading flatbuffers-2.0-py2.py3-none-any.whl (26 kB)
Collecting typing-extensions>=3.6.2.1
  Downloading typing_extensions-4.0.1-py3-none-any.whl (22 kB)
Collecting six
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting threadpoolctl>=2.0.0
  Using cached threadpoolctl-3.0.0-py3-none-any.whl (14 kB)
Collecting scipy>=1.1.0
  Downloading scipy-1.7.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (39.3 MB)
     |████████████████████████████████| 39.3 MB 52.9 MB/s 
Collecting joblib>=0.11
  Using cached joblib-1.1.0-py2.py3-none-any.whl (306 kB)
Building wheels for collected packages: ont-remora
  Building wheel for ont-remora (PEP 517) ... done
  Created wheel for ont-remora: filename=ont_remora-0.1.1-cp38-cp38-linux_x86_64.whl size=15350084 sha256=13147a2391f69bcb3473967dbe260b507877ab37007a79bdc32a36c710435ae0
  Stored in directory: /home/billylau/.cache/pip/wheels/65/3f/90/2d990ece00be8f22d2aa09b387689ff7bfa2eb4f361ae5d7aa
Successfully built ont-remora
Installing collected packages: typing-extensions, numpy, torch, threadpoolctl, six, scipy, protobuf, joblib, flatbuffers, tqdm, thop, tabulate, scikit-learn, onnxruntime, onnx, ont-remora
Successfully installed flatbuffers-2.0 joblib-1.1.0 numpy-1.21.4 onnx-1.10.2 onnxruntime-1.9.0 ont-remora-0.1.1 protobuf-3.19.1 scikit-learn-1.0.1 scipy-1.7.3 six-1.16.0 tabulate-0.8.9 thop-0.0.31.post2005241907 threadpoolctl-3.0.0 torch-1.10.0 tqdm-4.62.3 typing-extensions-4.0.1
(remora) billylau@suzuki:~$ remora model list_pretrained
Traceback (most recent call last):
  File "/home/billylau/.conda/envs/remora/bin/remora", line 8, in <module>
    sys.exit(run())
  File "/home/billylau/.conda/envs/remora/lib/python3.8/site-packages/remora/main.py", line 67, in run
    cmd_func(args)
  File "/home/billylau/.conda/envs/remora/lib/python3.8/site-packages/remora/parsers.py", line 560, in run_list_pretrained
    from remora.model_util import get_pretrained_models
  File "/home/billylau/.conda/envs/remora/lib/python3.8/site-packages/remora/model_util.py", line 10, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
(remora) billylau@suzuki:~$ conda install pandas
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /home/billylau/.conda/envs/remora:

The following NEW packages will be INSTALLED:

    blas:            1.0-mkl               
    bottleneck:      1.3.2-py38heb32a55_1  
    intel-openmp:    2021.4.0-h06a4308_3561
    mkl:             2021.4.0-h06a4308_640 
    mkl-service:     2.4.0-py38h7f8727e_0  
    mkl_fft:         1.3.1-py38hd3c417c_0  
    mkl_random:      1.2.2-py38h51133e4_0  
    numexpr:         2.7.3-py38h22e1b3c_1  
    numpy:           1.21.2-py38h20f2e39_0 
    numpy-base:      1.21.2-py38h79a1101_0 
    pandas:          1.3.4-py38h8c16a72_0  
    python-dateutil: 2.8.2-pyhd3eb1b0_0    
    pytz:            2021.3-pyhd3eb1b0_0   
    six:             1.16.0-pyhd3eb1b0_0   

Proceed ([y]/n)? y

mkl-service-2. 100% |##################################################################################################################################################################################| Time: 0:00:00  16.51 MB/s
numpy-base-1.2 100% |##################################################################################################################################################################################| Time: 0:00:00  81.29 MB/s
bottleneck-1.3 100% |##################################################################################################################################################################################| Time: 0:00:00  27.95 MB/s
mkl_fft-1.3.1- 100% |##################################################################################################################################################################################| Time: 0:00:00  29.60 MB/s
mkl_random-1.2 100% |##################################################################################################################################################################################| Time: 0:00:00  31.75 MB/s
numpy-1.21.2-p 100% |##################################################################################################################################################################################| Time: 0:00:00  15.87 MB/s
numexpr-2.7.3- 100% |##################################################################################################################################################################################| Time: 0:00:00  29.95 MB/s
pandas-1.3.4-p 100% |##################################################################################################################################################################################| Time: 0:00:00  29.95 MB/s
(remora) billylau@suzuki:~$ remora model list_pretrained
[10:40:16] Remora pretrained modified base models:
Pore             Basecall_Model_Type    Basecall_Model_Version    Modified_Bases    Remora_Model_Type      Remora_Model_Version
---------------  ---------------------  ------------------------  ----------------  -------------------  ----------------------
dna_r9.4.1_e8    fast                   0.0.0                     5mc               CG                                        0
dna_r9.4.1_e8    fast                   0.0.0                     5hmc_5mc          CG                                        0
dna_r9.4.1_e8    hac                    0.0.0                     5mc               CG                                        0
dna_r9.4.1_e8    hac                    0.0.0                     5hmc_5mc          CG                                        0
dna_r9.4.1_e8    sup                    0.0.0                     5mc               CG                                        0
dna_r9.4.1_e8    sup                    0.0.0                     5hmc_5mc          CG                                        0
dna_r9.4.1_e8.1  fast                   0.0.0                     5mc               CG                                        0
dna_r9.4.1_e8.1  hac                    0.0.0                     5mc               CG                                        0
dna_r9.4.1_e8.1  sup                    0.0.0                     5mc               CG                                        0
dna_r10.4_e8.1   fast                   0.0.0                     5mc               CG                                        0
dna_r10.4_e8.1   fast                   0.0.0                     5hmc_5mc          CG                                        0
dna_r10.4_e8.1   hac                    0.0.0                     5mc               CG                                        0
dna_r10.4_e8.1   hac                    0.0.0                     5hmc_5mc          CG                                        0
dna_r10.4_e8.1   sup                    0.0.0                     5mc               CG                                        0
dna_r10.4_e8.1   sup                    0.0.0                     5hmc_5mc          CG                                        0
(remora) billylau@suzuki:~$ 
```

**Comment by marcus1487** [comment]
This is a bug and has now been fixed in github and will be included in the next release. Thank you for flagging this issue!
