### ISSUE TITLE
export older remora model as dorado format

### ISSUE THREAD

**Issue by Yijun-Tian** [nanoporetech/remora#126]
Hi,
For remora v1.1.1, there is a R9 base modification model for 5hmCG and 5mCG:
```
.local/bin/remora model list_pretrained
[21:55:04] Remora pretrained modified base models:
Pore              Basecall_Model_Type    Basecall_Model_Version    Modified_Bases    Remora_Model_Type      Remora_Model_Version
----------------  ---------------------  ------------------------  ----------------  -------------------  ----------------------
dna_r9.4.1_e8     fast                   0.0.0                     5mc               CG                                        0
dna_r9.4.1_e8     fast                   0.0.0                     5hmc_5mc          CG                                        0
dna_r9.4.1_e8     hac                    0.0.0                     5mc               CG                                        0
dna_r9.4.1_e8     hac                    0.0.0                     5hmc_5mc          CG                                        0
dna_r9.4.1_e8     sup                    0.0.0                     5mc               CG                                        0
dna_r9.4.1_e8     sup                    0.0.0                     5hmc_5mc          CG                                        0
```
Is there a way to export the sup dual mod model into dorado format to make the calling faster? Currently the megalodon is too slow for calling using guppy.
Thanks,

**Comment by marcus1487** [comment]
The `remora model export` command should suffice for this purpose.

**Comment by Yijun-Tian** [comment]
Hi @marcus1487,
I just searched the v1.1.1 remora lib directory and found a trained_models folder containing onnx model files. I tried with newest remora to export, but got error:
```
(remora) 4470655@red2 ~]$ remora model export --format torchscript ~/.local/lib/python3.9/site-packages/remora/trained_models/dna_r9.4.1_e8/sup/0.0.0/5hmc_5mc/CG/v0/modbase
_model.onnx ~/dorado_models/test@r9
[09:22:08] Loading model
Traceback (most recent call last):
  File "/home/4470655/venv/lib/python3.8/site-packages/remora/parsers.py", line 732, in run_model_export
    model, ckpt = load_torchscript_model(args.checkpoint_path)
  File "/home/4470655/venv/lib/python3.8/site-packages/remora/model_util.py", line 395, in load_torchscript_model
    model = torch.jit.load(
  File "/home/4470655/venv/lib/python3.8/site-packages/torch/jit/_serialization.py", line 162, in load
    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files, _restore_shapes)  # type: ignore[call-arg]
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/4470655/venv/bin/remora", line 8, in <module>
    sys.exit(run())
  File "/home/4470655/venv/lib/python3.8/site-packages/remora/main.py", line 71, in run
    cmd_func(args)
  File "/home/4470655/venv/lib/python3.8/site-packages/remora/parsers.py", line 735, in run_model_export
    ckpt, model = continue_from_checkpoint(
  File "/home/4470655/venv/lib/python3.8/site-packages/remora/model_util.py", line 241, in continue_from_checkpoint
    ckpt = torch.load(ckp_path, map_location="cpu")
  File "/home/4470655/venv/lib/python3.8/site-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/4470655/venv/lib/python3.8/site-packages/torch/serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x08'.
```

Could you share more details of how this could be achieved?
Thank you,

**Comment by marcus1487** [comment]
Ah. Unfortunately, we do not have a method for converting onnx models to the pytorch or dorado formats. This was part of our reasoning for dropping the onnx model release format. Apologies for this inconvenience.

**Comment by Yijun-Tian** [comment]
Thank you @marcus1487 for confirming that.
