### ISSUE TITLE
Support for read splitting for ```dorado``` basecalled datasets

### ISSUE THREAD

**Issue by drivenbyentropy** [nanoporetech/remora#134]
@marcus1487 first of, congratulations on the long awaited release of remora v3.0.0! I am looking forward to using the new features and benefiting for the much improved documentation in the notebooks. 

While working an extended set of sequencing runs, I noticed that in certain scenarios, the following code would fail (assume we have a valid ```ref_reg``` instance):
```python 

from remora import io, refine_signal_map, util

can_pod5_fh = pod5.Reader("/path/to/pod5/output.pod5")
can_bam_fh = pysam.AlignmentFile("/path/to/output.bam")

bam_reads = io.get_reg_bam_reads(ref_reg, can_bam_fh)
io_reads = io.get_io_reads(bam_reads, can_pod5_fh, reverse_signal=False)
```

```python 
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_4172874/380764999.py in <module>
      6 
      7 bam_reads = io.get_reg_bam_reads(ref_reg, can_bam_fh)
----> 8 io_reads = io.get_io_reads(bam_reads, can_pod5_fh, reverse_signal=False)

/[...]/python3.9/site-packages/pod5/reader.py in reads(self, selection, missing_ok, preload)
    930             yield from self._reads(preload=preload)
    931         else:
--> 932             yield from self._select_reads(
    933                 list(selection), missing_ok=missing_ok, preload=preload
    934             )

/[...]/python3.9/site-packages/pod5/reader.py in _select_reads(self, selection, missing_ok, preload)
    949     ) -> Generator[ReadRecord, None, None]:
    950         """Generate selected reads"""
--> 951         for batch in self._select_read_batches(selection, missing_ok, preload=preload):
    952             for read in batch.reads():
    953                 yield read

/[...]/python3.9/site-packages/pod5/reader.py in _select_read_batches(self, selection, missing_ok, preload)
   1002 
   1003         if not missing_ok and successful_finds != len(selection):
-> 1004             raise RuntimeError(
   1005                 f"Failed to find {len(selection) - successful_finds} requested reads in the file"
   1006             )

RuntimeError: Failed to find 8679 requested reads in the file
```

I have opened an [issue](github.com/nanoporetech/dorado/issues/476) in ```dorados``` github which pointed me towards this being caused due to [read splitting](https://github.com/nanoporetech/dorado/blob/master/documentation/SAM.md#split-read-tags), which is active by default in ```dorado```.  

I assume that the reason for this could be because ```missing_ok``` is not propagated to ```reads()``` in [```read_pod5_reads()```](https://github.com/nanoporetech/remora/blob/5a8e02092f4e28739d443119776916b0f5a2d11d/src/remora/io.py#L737C5-L737C19) and I believe the reason for this is to ensure that the bam_read list and io_read list always have the same order.

I was wondering if it would be possible to extend the remora API to support read splitting by default. I am currently overcoming this issue by manually filtering the ```bam_reads``` for split reads prior to calling ```io.get_io_reads()```.

Thank you and I am looking forward to your input.

**Comment by marcus1487** [comment]
I see the issue here. I've enabled split read support for all command line interfaces, but did not test the core API elements for split read support. I will fix this and push a hot fix to address the extraction of io_reads correctly.

**Comment by marcus1487** [comment]
I've just pushed a fix to github. If you can update with `pip install git+https://github.com/nanoporetech/remora.git` and test this that would be great. I will include this fix in a patch release soon.

**Comment by drivenbyentropy** [comment]
@marcus1487, Thank you for the fix. When trying to load the io_reads now, I get the following error
```python
Traceback (most recent call last):
  File "[..]/python3.9/site-packages/remora/io.py", line 1888, in add_alignment
    self.num_trimmed = tags["ts"] + tags["sp"]
KeyError: 'sp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[..]/python3.9/site-packages/remora/io.py", line 756, in get_io_reads
    io_read = Read.from_pod5_and_alignment(
  File "[..]/python3.9/site-packages/remora/io.py", line 1992, in from_pod5_and_alignment
    read.add_alignment(alignment_record, reverse_signal=reverse_signal)
  File "[..]/python3.9/site-packages/remora/io.py", line 1894, in add_alignment
    raise RemoraError("Split read missing sp tag")
remora.RemoraError: Split read missing sp tag

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[...].py", line 129, in <module>
    io_reads = io.get_io_reads(bam_reads, can_pod5_fh, reverse_signal=False)
  File "[..]/python3.9/site-packages/remora/io.py", line 765, in get_io_reads
    raise RemoraError("BAM record not found in POD5")
remora.RemoraError: BAM record not found in POD5
```

I used the standard parameters in ```dorado``` while base calling as described [here](https://github.com/nanoporetech/dorado/issues/476).

**Comment by marcus1487** [comment]
The `sp` (split point) tag was added in dorado v4.3 to enable the processing of split read signal extraction. If you upgrade to the latest dorado version and re-basecall this should resolve this issue.

**Comment by drivenbyentropy** [comment]
Thanks, will do and report back.

**Comment by drivenbyentropy** [comment]
@marcus1487, I completed basecalling using ```dorado``` 4.3 and as you predicted, this solved the issue. The API now does correctly handle split read signals. Thanks for the fix!
