### ISSUE TITLE
Unknown error in resquiggle command

### ISSUE THREAD

**Issue by CarolinaA09** [nanoporetech/remora#167]
Hi, I am using this command to resquiggle my RNA data:

remora dataset prepare pod5_dir file.bam --output-path mod_chunks --refine-kmer-level-table 5mer_levels_v1.txt --refine-rough-rescale --motif CG 0 --mod-base m 5mC --reverse-signal --overwrite
 
But, I am getting an error. I am not sure what it is about:

Traceback (most recent call last):
  File "/nas/longleaf/home/caroe/.local/bin/remora", line 8, in <module>
    sys.exit(run())
  File "/nas/longleaf/home/caroe/.local/lib/python3.10/site-packages/remora/main.py", line 71, in run
    cmd_func(args)
  File "/nas/longleaf/home/caroe/.local/lib/python3.10/site-packages/remora/parsers.py", line 290, in run_dataset_prepare
    sig_map_refiner = SigMapRefiner(
  File "<string>", line 17, in __init__
  File "/nas/longleaf/home/caroe/.local/lib/python3.10/site-packages/remora/refine_signal_map.py", line 294, in __post_init__
    self.load_kmer_table()
  File "/nas/longleaf/home/caroe/.local/lib/python3.10/site-packages/remora/refine_signal_map.py", line 230, in load_kmer_table
    self.kmer_len = len(kmer_fp.readline().split()[0])
IndexError: list index out of range

I would greatly appreciate your input.

Kind regards,

CA

**Comment by marcus1487** [comment]
It looks like the first line of your file `5mer_levels_v1.txt` is empty. Could you check that this file is not empty?

**Comment by CarolinaA09** [comment]
Indeed thanks! It was improperly retrieved! Thank you.
