### ISSUE TITLE
Resquiggle

### ISSUE THREAD

**Issue by JSluo888** [nanoporetech/remora#179]
I understand that Tombo is deprecated, but I would need to use resquiggle from tombo before running other programs. Is there a similar command in Remora?

The reason I ask is that I encountered the following error when running the tombo resquiggle:
`Traceback (most recent call last):
  File "/home3/prallw/miniconda3/envs/tandem/lib/python3.7/site-packages/tombo/resquiggle.py", line 1404, in _io_and_map_read
    map_thr_buf, q_score_thresh, seq_len_rng)
  File "/home3/prallw/miniconda3/envs/tandem/lib/python3.7/site-packages/tombo/resquiggle.py", line 1336, in map_read
    seq_data.id.decode(), bc_subgrp, num_start_clipped_bases,
AttributeError: 'str' object has no attribute 'decode'`

**Comment by marcus1487** [comment]
The notebooks section of the repository contains details of how to apply sequence to signal alignment (re-squiggle). If there are some details missing there please describe them in more detail here.

**Comment by JSluo888** [comment]
Thanks! I am still a bit confused -- the notebook contains steps to create plots etc, but all I need to do is to have resquiggled reads as fast5 files. Could you please specify which specific command/line I should run in order to do that?

**Comment by marcus1487** [comment]
Presumably storing the resquiggle results is not the final goal. Remora has specifically removed any specified output format for sequence to signal mappings. The idea here is that resquiggle results should be computed on the fly and used for the final goal instead of stored in a format that might not be ideal for all applications. If you could detail the desired final analysis I would be happy to figure out how the remora api can assist.
