### ISSUE TITLE
Not enough chunks

### ISSUE THREAD

**Issue by TKsh6** [nanoporetech/remora#189]
Hellow, I uese the data in test dir to run remora, but when I was training I got this problem,
```
(remora) syl@asus:~/software/remora/remora-master/tests$ remora   model train   test/train_dataset.jsn   --model /mnt/raid/syl/software/remora/remora-master/models/ConvLSTM_w_ref.py   --device 0   --chunk-context 200 200   --output-path test/train_results
[10:03:25.203] Seed selected is 1420555017
[10:03:25.219] Loading dataset from Remora dataset config
[10:03:25.238] Dataset summary:
                     size : 415
     modified_base_labels : True
                mod_bases : ['m']
           mod_long_names : ['5mC']
       kmer_context_bases : (4, 4)
            chunk_context : (200, 200)
                   motifs : [('CG', 0)]
           reverse_signal : False
 chunk_extract_base_start : False
     chunk_extract_offset : 0
               pa_scaling : None
          sig_map_refiner : Loaded 9-mer table with 7 central position. Rough re-scaling will be executed.

[10:03:25.238] Loading model
[10:03:25.245] Model structure:
network(
  (sig_conv1): Conv1d(1, 4, kernel_size=(5,), stride=(1,))
  (sig_bn1): BatchNorm1d(4, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (sig_conv2): Conv1d(4, 16, kernel_size=(5,), stride=(1,))
  (sig_bn2): BatchNorm1d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (sig_conv3): Conv1d(16, 64, kernel_size=(9,), stride=(3,))
  (sig_bn3): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (seq_conv1): Conv1d(36, 16, kernel_size=(5,), stride=(1,))
  (seq_bn1): BatchNorm1d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (seq_conv2): Conv1d(16, 64, kernel_size=(13,), stride=(3,))
  (seq_bn2): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (merge_conv1): Conv1d(128, 64, kernel_size=(5,), stride=(1,))
  (merge_bn): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (lstm1): LSTM(64, 64)
  (lstm2): LSTM(64, 64)
  (fc): Linear(in_features=64, out_features=2, bias=True)
  (dropout): Dropout(p=0.3, inplace=False)
)
[10:03:25.245] Gradients will be clipped (by value) at 0.00 MADs above the median of the last 1000 gradient maximums.
[10:03:26.202] Params (k) 134.08 | MACs (M) 36395.12
[10:03:26.202] Preparing training settings
[10:03:26.454] Training optimizer and scheduler settings: TrainOpts(epochs=100, early_stopping=10, optimizer_str='AdamW', opt_kwargs=(('weight_decay', 0.0001, 'float'),), learning_rate=0.001, lr_scheduler_str='CosineAnnealingLR', lr_scheduler_kwargs=(('T_max', 100, 'int'), ('eta_min', 1e-06, 'float')), lr_cool_down_epochs=5, lr_cool_down_lr=1e-07)
Traceback (most recent call last):
  File "/mnt/raid/syl/.local/bin/remora", line 8, in <module>
    sys.exit(run())
  File "/mnt/raid/syl/.local/lib/python3.8/site-packages/remora/main.py", line 71, in run
    cmd_func(args)
  File "/mnt/raid/syl/.local/lib/python3.8/site-packages/remora/parsers.py", line 1008, in run_model_train
    train_model(
  File "/mnt/raid/syl/.local/lib/python3.8/site-packages/remora/train_model.py", line 356, in train_model
    trn_ds, val_ds = dataset.train_test_split(
  File "/mnt/raid/syl/.local/lib/python3.8/site-packages/remora/data_chunks.py", line 2104, in train_test_split
    raise RemoraError("Not enough chunks")
remora.RemoraError: Not enough chunks
```
So, is this the volume of insufficient data?
If you have some ideas, please recontact with me, thx :)

**Comment by marcus1487** [comment]
The default number of validation chunks held out from the training data is 10,000 and the test data has less than 500 valid chunks. Setting the number of validation chunk arguments to a smaller number will allow the training command to run, but we generally recommend at least 1 million and generally 20-30 million chunks to train a relatively robust model. The production release models are trained from over 1 billions chunks.
