### ISSUE TITLE
Using remora model train miss the error "double free or corruption (out)  Aborted (核心已转储)" 

### ISSUE THREAD

**Issue by ZhouShibo0823** [nanoporetech/remora#196]
When using the command line "remora model train train_dataset.jsn --model ~/gpfs1/Software/remora/models/ConvLSTM_w_ref.py --chunk-context 50 50 --output-path train_results --overwrite",  it got the output as follow:
[03:33:02.898] Seed selected is 3611860209
[03:33:02.921] Loading dataset from Remora dataset config
[03:33:03.155] Dataset summary:
                     size : 180,000
       kmer context bases : (4, 4)
            chunk context : (50, 50)
           reverse signal : False
 chunk extract base start : False
     chunk extract offset : 0
               pa scaling : None
          sig map refiner : Loaded 9-mer table with 7 central position. Rough re-scaling will be executed.
        batches preloaded : False
      is modbase dataset? : True
                mod bases : ['m']
           mod long names : ['5mC']
                   motifs : [('C', 0)]

[03:33:03.158] Loading model
[03:33:03.180] Model structure:
network(
  (sig_conv1): Conv1d(1, 4, kernel_size=(5,), stride=(1,))
  (sig_bn1): BatchNorm1d(4, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (sig_conv2): Conv1d(4, 16, kernel_size=(5,), stride=(1,))
  (sig_bn2): BatchNorm1d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (sig_conv3): Conv1d(16, 64, kernel_size=(9,), stride=(3,))
  (sig_bn3): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (seq_conv1): Conv1d(36, 16, kernel_size=(5,), stride=(1,))
  (seq_bn1): BatchNorm1d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (seq_conv2): Conv1d(16, 64, kernel_size=(13,), stride=(3,))
  (seq_bn2): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (merge_conv1): Conv1d(128, 64, kernel_size=(5,), stride=(1,))
  (merge_bn): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (lstm1): LSTM(64, 64)
  (lstm2): LSTM(64, 64)
  (fc): Linear(in_features=64, out_features=2, bias=True)
  (dropout): Dropout(p=0.3, inplace=False)
)
[03:33:03.180] Gradients will be clipped (by value) at 0.00 MADs above the median of the last 1000 gradient maximums.
[03:33:03.505] Params (k) 134.08 | MACs (M) 7327.45
[03:33:03.506] Preparing training settings
[03:33:03.507] Training optimizer and scheduler settings: TrainOpts(epochs=100, early_stopping=10, optimizer_str='AdamW', opt_kwargs=(('weight_decay', 0.0001, 'float'),), learning_rate=0.001, lr_scheduler_str='CosineAnnealingLR', lr_scheduler_kwargs=(('T_max', 100, 'int'), ('eta_min', 1e-06, 'float')), lr_cool_down_epochs=5, lr_cool_down_lr=1e-07)
double free or corruption (out)
Aborted (核心已转储)

So what's wrong according to this error, and how can i do to address it ?
Wait for you quick reply

**Comment by ZhouShibo0823** [comment]
When I reset the parameter "--chunk-context " from 50 50 to 200 200 as follow
remora model train train_dataset.jsn --model ~/gpfs1/Software/remora/models/ConvLSTM_w_ref.py --chunk-context 200 200 --output-path train_results --overwrite

I got the output:
[16:02:43.637] Seed selected is 64769119
[16:02:43.640] Loading dataset from Remora dataset config
[16:02:43.798] Dataset summary:
                     size : 180,000
       kmer context bases : (4, 4)
            chunk context : (200, 200)
           reverse signal : False
 chunk extract base start : False
     chunk extract offset : 0
               pa scaling : None
          sig map refiner : Loaded 9-mer table with 7 central position. Rough re-scaling will be executed.
        batches preloaded : False
      is modbase dataset? : True
                mod bases : ['m']
           mod long names : ['5mC']
                   motifs : [('C', 0)]

[16:02:43.800] Loading model
[16:02:43.822] Model structure:
network(
  (sig_conv1): Conv1d(1, 4, kernel_size=(5,), stride=(1,))
  (sig_bn1): BatchNorm1d(4, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (sig_conv2): Conv1d(4, 16, kernel_size=(5,), stride=(1,))
  (sig_bn2): BatchNorm1d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (sig_conv3): Conv1d(16, 64, kernel_size=(9,), stride=(3,))
  (sig_bn3): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (seq_conv1): Conv1d(36, 16, kernel_size=(5,), stride=(1,))
  (seq_bn1): BatchNorm1d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (seq_conv2): Conv1d(16, 64, kernel_size=(13,), stride=(3,))
  (seq_bn2): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (merge_conv1): Conv1d(128, 64, kernel_size=(5,), stride=(1,))
  (merge_bn): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (lstm1): LSTM(64, 64)
  (lstm2): LSTM(64, 64)
  (fc): Linear(in_features=64, out_features=2, bias=True)
  (dropout): Dropout(p=0.3, inplace=False)
)
[16:02:43.823] Gradients will be clipped (by value) at 0.00 MADs above the median of the last 1000 gradient maximums.
[16:02:44.514] Params (k) 134.08 | MACs (M) 36395.12
[16:02:44.514] Preparing training settings
[16:02:44.514] Training optimizer and scheduler settings: TrainOpts(epochs=100, early_stopping=10, optimizer_str='AdamW', opt_kwargs=(('weight_decay', 0.0001, 'float'),), learning_rate=0.001, lr_scheduler_str='CosineAnnealingLR', lr_scheduler_kwargs=(('T_max', 100, 'int'), ('eta_min', 1e-06, 'float')), lr_cool_down_epochs=5, lr_cool_down_lr=1e-07)
[16:02:45.926] Dataset loaded with labels: control:180,000; 5mC:0
[16:02:45.927] Train labels: control:170,000; 5mC:0
[16:02:45.927] Held-out validation labels: control:8,192; 5mC:0
[16:02:45.928] Training set validation labels: control:8,192; 5mC:0
[16:02:45.928] Running initial validation
Batches: 0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/lustre2/jdhan_pkuhpc/common/mamba/envs/nanopore/bin/remora", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/lustre2/jdhan_pkuhpc/common/mamba/envs/nanopore/lib/python3.12/site-packages/remora/main.py", line 71, in run
    cmd_func(args)
  File "/lustre2/jdhan_pkuhpc/common/mamba/envs/nanopore/lib/python3.12/site-packages/remora/parsers.py", line 1377, in run_model_train
    train_model(
  File "/lustre2/jdhan_pkuhpc/common/mamba/envs/nanopore/lib/python3.12/site-packages/remora/train_model.py", line 379, in train_model
    val_metrics = val_fp.validate_model(
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre2/jdhan_pkuhpc/common/mamba/envs/nanopore/lib/python3.12/site-packages/remora/validate.py", line 282, in validate_model
    ms = self.run_validation(
         ^^^^^^^^^^^^^^^^^^^^
  File "/lustre2/jdhan_pkuhpc/common/mamba/envs/nanopore/lib/python3.12/site-packages/remora/validate.py", line 236, in run_validation
    output = model(sigs, enc_kmers).detach().cpu().numpy()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre2/jdhan_pkuhpc/common/mamba/envs/nanopore/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre2/jdhan_pkuhpc/common/mamba/envs/nanopore/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre2/jdhan_pkuhpc/zhoushibo/nanopore/nanopore_20241122ac1/no_sample/20230302_1348_MC-116227_FBA90257_1a3ba3c0/remora/m5c/train_results/model.py", line 45, in forward
    seqs_x = swish(self.seq_bn1(self.seq_conv1(seqs)))
                                ^^^^^^^^^^^^^^^^^^^^
  File "/lustre2/jdhan_pkuhpc/common/mamba/envs/nanopore/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre2/jdhan_pkuhpc/common/mamba/envs/nanopore/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre2/jdhan_pkuhpc/common/mamba/envs/nanopore/lib/python3.12/site-packages/torch/nn/modules/conv.py", line 375, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre2/jdhan_pkuhpc/common/mamba/envs/nanopore/lib/python3.12/site-packages/torch/nn/modules/conv.py", line 370, in _conv_forward
    return F.conv1d(
           ^^^^^^^^^
RuntimeError: Calculated padded input size per channel: (0). Kernel size: (5). Kernel size can't be greater than actual input size
I wonder if  it is the chunk-context affect the output error, if so,how can I choose the suitable parameter

**Comment by marcus1487** [comment]
The standard remora model takes in both sequence and signal and applies separate convolutions to these two inputs before merging the features and running the rest of the network. It appears that you have possibly made alterations to the network architecture making the merge step invalid. You'll have to construct a valid network architecture in order to train a model. Please let me know if the standard architecture solves this issue.

**Comment by ZhouShibo0823** [comment]
In fact, I am following the Remora pipeline, and the model I used was also directly downloaded from the remora/models on GitHub. Before training the Remora model, I used the following commands:

”remora dataset prepare ./pod5/merge_modified.pod5 modified_call_simplex_mapped.bam --output-path mod_chunks_dataset --refine-kmer-level-table 9mer_levels_v1.txt --refine-rough-rescale --mod-base m 5mC --motif C 0 --overwrite
remora dataset prepare ./pod5/merge_canonical.pod5 canonical_call_simplex_mapped.bam --output-path can_chunks_dataset --refine-kmer-level-table 9mer_levels_v1.txt --refine-rough-rescale --mod-base-control --motif C 0 --overwrite
remora dataset make_config train_dataset.jsn can_chunks_dataset mod_chunks_dataset --dataset-weights 1 1 --log-filename train_dataset.log“

”modified_call_simplex_mapped.bam“ and ”canonical_call_simplex_mapped.bam“ are both BAM files obtained from ONT nanopore sequencing data processed by Dorado. They were generated using the command:

samtools fastq -T "*" canonical_call_simplex.bam | minimap2 -y -ax lr:hq m5C_control.fa - | samtools view -b -o canonical_call_simplex_mapped.bam

**Comment by spoweekkk** [comment]
I have figured out the reason. It was because I didn't using arguement --MD when using minimap2, which caused there were no MD tag in bam files

**Comment by ZhouShibo0823** [comment]
I have figured out the reason. It was because I didn't use arguement --MD when using minimap2, which caused there were no MD tag in bam files
