### ISSUE TITLE
Error running remora infer

### ISSUE THREAD

**Issue by johannesnicolaus** [nanoporetech/remora#198]
I tried to run the following command on a bam file called using Dorado v0.83. The pod5 file was converted from fast5 using `pod5 convert fast5`.

```
remora \
  infer from_pod5_and_bam \
   converted.pod5 \
   calls.bam \
  --modified-bases m 6ma \
  --model ${modeldir}/res_dna_r10.4.1_e8.2_4khz_400bps_sup_v4.0.1_6mA_v2.pt \
  --out-bam can_infer.bam \
  --log-filename can_infer.log 
```

I got the following error, which I'm totally unsure what happened.
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/remora/model_util.py", line 593, in load_model
    return load_torchscript_model(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/remora/model_util.py", line 558, in load_torchscript_model
    model, model_metadata = _raw_load_torchscript_model(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/remora/model_util.py", line 479, in _raw_load_torchscript_model
    model = torch.jit.load(
            ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/jit/_serialization.py", line 163, in load
    cpp_module = torch._C.import_ir_module(cu, os.fspath(f), map_location, _extra_files, _restore_shapes)  # type: ignore[call-arg]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/remora", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/usr/local/lib/python3.11/dist-packages/remora/main.py", line 71, in run
    cmd_func(args)
  File "/usr/local/lib/python3.11/dist-packages/remora/parsers.py", line 1966, in run_infer_from_pod5_and_bam
    models = [
             ^
  File "/usr/local/lib/python3.11/dist-packages/remora/parsers.py", line 1967, in <listcomp>
    load_model(**model_kwargs, quiet=False, eval_only=True)
  File "/usr/local/lib/python3.11/dist-packages/remora/model_util.py", line 597, in load_model
    raise RemoraError("Failed loading torchscript model.")
remora.RemoraError: Failed loading torchscript model.

```

The following is the command I used to generate the files
```
dorado basecaller --emit-moves -v hac,5mCG_5hmCG converted.pod5 > calls.bam

```

I installed remora using pip as shown in the github README.

**Comment by marcus1487** [comment]
I'm wondering if this is a torch version issue. What version are you using? Could you try downgrading to torch<2 and report if this solves the issue?

**Comment by marcus1487** [comment]
Googling seems to indicate a corrupted file. Can you also try to download the model again?

**Comment by alvinwt** [comment]
I have the same error and I think it is due to not being able to download the model. 


```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message></Error>
```
