### ISSUE TITLE
'Remora model list_pretrained'

### ISSUE THREAD

**Issue by Flower9618** [nanoporetech/remora#24]
Hello. Thank you very much for sharing this useful tool.
When I install from github source for development, and run 'remora model list_pretrtained', there is an error:
'''
Traceback (most recent call last):
  File "/lustre/home/rongqiao/anaconda3/envs/remora1.1.0-env/bin/remora", line 33, in <module>
    sys.exit(load_entry_point('ont-remora', 'console_scripts', 'remora')())
  File "/lustre/home/rongqiao/remora1.1.0/remora/src/remora/main.py", line 69, in run
    cmd_func(args)
  File "/lustre/home/rongqiao/remora1.1.0/remora/src/remora/parsers.py", line 674, in run_list_pretrained
    from remora.model_util import get_pretrained_models
  File "/lustre/home/rongqiao/remora1.1.0/remora/src/remora/model_util.py", line 11, in <module>
    import onnx
  File "/lustre/home/rongqiao/anaconda3/envs/remora1.1.0-env/lib/python3.8/site-packages/onnx/__init__.py", line 11, in <module>
    from onnx.external_data_helper import load_external_data_for_model, write_external_data_tensors, convert_model_to_external_data
  File "/lustre/home/rongqiao/anaconda3/envs/remora1.1.0-env/lib/python3.8/site-packages/onnx/external_data_helper.py", line 14, in <module>
    from .onnx_pb import TensorProto, ModelProto
  File "/lustre/home/rongqiao/anaconda3/envs/remora1.1.0-env/lib/python3.8/site-packages/onnx/onnx_pb.py", line 8, in <module>
    from .onnx_ml_pb2 import *  # noqa
  File "/lustre/home/rongqiao/anaconda3/envs/remora1.1.0-env/lib/python3.8/site-packages/onnx/onnx_ml_pb2.py", line 33, in <module>
    _descriptor.EnumValueDescriptor(
  File "/lustre/home/rongqiao/anaconda3/envs/remora1.1.0-env/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 755, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
'''

Is this because I install the package from github source?

**Comment by marcus1487** [comment]
This is a known issue. It appears that one of the dependencies for ONNX models (the storage format for Remora models) has been updated to make the current files invalid. This dependency version will be fixed in Remora shortly.

**Comment by Flower9618** [comment]
> This is a known issue. It appears that one of the dependencies for ONNX models (the storage format for Remora models) has been updated to make the current files invalid. This dependency version will be fixed in Remora shortly.

Thank you very much for your replying. But  I can still use remora to call base modification, is that right?

**Comment by edridgedsouza** [comment]
Bumping this because I'm experiencing the same issue. If base calling is not affected, could someone please provide a list of outputs of `remora model list_pretrained` from a working version? I'm simply trying to figure out what options to feed to megalodon but they aren't included in the documentation.

**Comment by marcus1487** [comment]
I've just pushed a new version (v1.1.1) with a fix for this. Please re-open this issue if these issues persist.

**Comment by edridgedsouza** [comment]
Thanks! Works now. In case anyone else runs into this issue going forward, here is the output of the command as of 2022-06-16:

```
$ remora model list_pretrained
[15:29:15] Remora pretrained modified base models:
Pore              Basecall_Model_Type    Basecall_Model_Version    Modified_Bases    Remora_Model_Type      Remora_Model_Version
----------------  ---------------------  ------------------------  ----------------  -------------------  ----------------------
dna_r9.4.1_e8     fast                   0.0.0                     5mc               CG                                        0
dna_r9.4.1_e8     fast                   0.0.0                     5hmc_5mc          CG                                        0
dna_r9.4.1_e8     hac                    0.0.0                     5mc               CG                                        0
dna_r9.4.1_e8     hac                    0.0.0                     5hmc_5mc          CG                                        0
dna_r9.4.1_e8     sup                    0.0.0                     5mc               CG                                        0
dna_r9.4.1_e8     sup                    0.0.0                     5hmc_5mc          CG                                        0
dna_r9.4.1_e8.1   fast                   0.0.0                     5mc               CG                                        0
dna_r9.4.1_e8.1   hac                    0.0.0                     5mc               CG                                        0
dna_r9.4.1_e8.1   sup                    0.0.0                     5mc               CG                                        0
dna_r10.4_e8.1    fast                   0.0.0                     5mc               CG                                        0
dna_r10.4_e8.1    fast                   0.0.0                     5mc               CG                                        1
dna_r10.4_e8.1    fast                   0.0.0                     5hmc_5mc          CG                                        0
dna_r10.4_e8.1    fast                   v3.3                      5mc               CG                                        0
dna_r10.4_e8.1    fast                   v3.3                      5mc               CG                                        1
dna_r10.4_e8.1    hac                    0.0.0                     5mc               CG                                        0
dna_r10.4_e8.1    hac                    0.0.0                     5mc               CG                                        1
dna_r10.4_e8.1    hac                    0.0.0                     5hmc_5mc          CG                                        0
dna_r10.4_e8.1    hac                    v3.3                      5mc               CG                                        0
dna_r10.4_e8.1    hac                    v3.3                      5mc               CG                                        1
dna_r10.4_e8.1    sup                    0.0.0                     5mc               CG                                        0
dna_r10.4_e8.1    sup                    0.0.0                     5mc               CG                                        1
dna_r10.4_e8.1    sup                    0.0.0                     5hmc_5mc          CG                                        0
dna_r10.4_e8.1    sup                    v3.4                      5mc               CG                                        0
dna_r10.4_e8.1    sup                    v3.4                      5mc               CG                                        1
dna_r10.4.1_e8.2  fast                   0.0.0                     5mc               CG                                        0
dna_r10.4.1_e8.2  fast                   0.0.0                     5mc               CG                                        1
dna_r10.4.1_e8.2  fast                   v3.5.1                    5mc               CG                                        0
dna_r10.4.1_e8.2  fast                   v3.5.1                    5mc               CG                                        1
dna_r10.4.1_e8.2  hac                    0.0.0                     5mc               CG                                        0
dna_r10.4.1_e8.2  hac                    0.0.0                     5mc               CG                                        1
dna_r10.4.1_e8.2  hac                    v3.5.1                    5mc               CG                                        0
dna_r10.4.1_e8.2  hac                    v3.5.1                    5mc               CG                                        1
dna_r10.4.1_e8.2  sup                    0.0.0                     5mc               CG                                        0
dna_r10.4.1_e8.2  sup                    0.0.0                     5mc               CG                                        1
dna_r10.4.1_e8.2  sup                    v3.5.1                    5mc               CG                                        0
dna_r10.4.1_e8.2  sup                    v3.5.1                    5mc               CG                                        1
```
