### ISSUE TITLE
Installing megalodon on python3.6 breaks remora

### ISSUE THREAD

**Issue by billytcl** [nanoporetech/remora#3]
I think there is some weird python incompatibility here. I installed megalodon on python3.6 because I needed to get the pyguppy api for guppy 5.0.16 (it doesn't exist for python 3.9). When typing in the following, I get an error:

```
[billylau@sh02-01n58 /scratch/groups/hanleeji/ONT_test/20211011_PRM_1096] (job 40324222) $ remora model list_pretrained
Traceback (most recent call last):
  File "/home/users/billylau/.local/bin/remora", line 8, in <module>
    sys.exit(run())
  File "/home/users/billylau/.local/lib/python3.6/site-packages/remora/main.py", line 67, in run
    cmd_func(args)
  File "/home/users/billylau/.local/lib/python3.6/site-packages/remora/parsers.py", line 560, in run_list_pretrained
    from remora.model_util import get_pretrained_models
  File "/home/users/billylau/.local/lib/python3.6/site-packages/remora/model_util.py", line 13, in <module>
    import torch
  File "/home/users/billylau/.local/lib/python3.6/site-packages/torch/__init__.py", line 573, in <module>
    import torch.quantization
  File "/home/users/billylau/.local/lib/python3.6/site-packages/torch/quantization/__init__.py", line 9, in <module>
    from .quantize_fx import *
  File "/home/users/billylau/.local/lib/python3.6/site-packages/torch/quantization/quantize_fx.py", line 1, in <module>
    from .fx import Fuser  # noqa: F401
  File "/home/users/billylau/.local/lib/python3.6/site-packages/torch/quantization/fx/__init__.py", line 1, in <module>
    from .quantize import Quantizer
  File "/home/users/billylau/.local/lib/python3.6/site-packages/torch/quantization/fx/quantize.py", line 2, in <module>
    from torch._fx import (
  File "/home/users/billylau/.local/lib/python3.6/site-packages/torch/_fx/__init__.py", line 89, in <module>
    from .symbolic_trace import symbolic_trace, Tracer
  File "/home/users/billylau/.local/lib/python3.6/site-packages/torch/_fx/symbolic_trace.py", line 9, in <module>
    from .proxy import Proxy, _create_proxy, TracerBase
  File "/home/users/billylau/.local/lib/python3.6/site-packages/torch/_fx/proxy.py", line 7, in <module>
    from typing import Tuple, Dict, Optional, Iterable, NoReturn, Any, Union, Callable
ImportError: cannot import name 'NoReturn'
```

When I install megalodon from scratch using python 3.9, that command works perfectly. I'm not sure why having a different python version would do this, though. Or maybe the problem is something else -- I noticed that it's trying to do something with torch.

**Comment by marcus1487** [comment]
This looks like an issue with pytorch (https://github.com/psf/black/issues/1666#issuecomment-685805740). Could you check your exact python version?

**Comment by billytcl** [comment]
It looks like the python 3.6 that was installed is 3.6.1, which is the one referred to in the pytorch issue!
