### ISSUE TITLE
question about 'remora infer' command

### ISSUE THREAD

**Issue by Flower9618** [nanoporetech/remora#33]
Hello, thank you so much for sharing this very useful tool.
When I use 'remora infer' command to call modification, I just set the parameters '--onnx model', '--output-path', '--overwrite' in additional to the required parameters. This command runs successfully and it run on the CPU. However, it runs so slowly and it shows it will finish after 150 hours.
So, I try to run 'remora infer' command on GPU device. After I install 'onnxruntime-gpu' package and run 'remora infer' after including '--device 0' parameter, there is an error message:

`Traceback (most recent call last):
  File "...", line 33, in <module>                          
    sys.exit(load_entry_point('ont-remora', 'console_scripts', 'remora')())                                                            
  File "/.../remora1.1.1/remora/src/remora/main.py", line 69, in run                                               
    cmd_func(args)
  File "/.../remora1.1.1/remora/src/remora/parsers.py", line 793, in run_infer_from_taiyaki_mapped_signal          
    from remora.inference import infer
  File "/.../remora1.1.1/remora/src/remora/inference.py", line 17, in <module>                                     
    from remora.model_util import load_model
  File "/.../remora1.1.1/remora/src/remora/model_util.py", line 7, in <module>                                     
    import pkg_resources
  File "/.../python3.8/site-packages/pkg_resources/__init__.py", line 3260, in <module>
    def _initialize_master_working_set():
  File "/.../python3.8/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/.../python3.8/site-packages/pkg_resources/__init__.py", line 3272, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/.../python3.8/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    ws.require(__requires__)
  File "/.../python3.8/site-packages/pkg_resources/__init__.py", line 909, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/.../python3.8/site-packages/pkg_resources/__init__.py", line 795, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'onnxruntime>=1.7' distribution was not found and is required by ont-remora`

I think it should not be the version error. Because when I run 'import onnxruntime' and 'onnxruntime.get_device()' in python, it will show 'GPU'. Like this:
`>>> import onnxruntime`
`>>> onnxruntime.get_device()`
`'GPU'`

I takes a lot of time to try to solve this problem, but still have no idea. I wonder if you have any advice to help me. Thank you very much.

**Comment by Flower9618** [comment]
I just find the problem. Because I do not install 'onnxruntime' package. Thank you very much.
