### ISSUE TITLE
Error when running with remora with megalodon 

### ISSUE THREAD

**Issue by pterzian** [nanoporetech/remora#35]
Hello,

Very excited to try this tool. I have a couple of ideas for some training but first I would like to try it with megalodon to compare results with previous work.

So far, I have created a py-venv to install remora and megalodon toguether. I am using ```guppy 5.0.17``` for basecalling.

Install seemed to be ok but I have this error when launching megalodon :

```
[17:51:50] Running Megalodon version 2.5.0
******************** WARNING: "mods" output requested, so "per_read_mods" will be added to outputs. ********************
[17:51:50] Loading guppy basecalling backend
[2022-09-28 17:51:54.560985] [0x00007efff5983700] [info]    Connecting to server as ''
[2022-09-28 17:51:54.563003] [0x00007efff5983700] [info]    Connected to server as ''. Connection id: 78acbf80-dc98-4661-9f48-347d898fe981
Traceback (most recent call last):
  File "/home/prom/.local/bin/megalodon", line 8, in <module>
    sys.exit(_main())
  File "/Nanopore/megalodon/megalodon/__main__.py", line 754, in _main
    megalodon._main(args)
  File "/Nanopore/megalodon/megalodon/megalodon.py", line 1797, in _main
    model_info = backends.ModelInfo(
  File "/Nanopore/megalodon/megalodon/backends.py", line 596, in __init__
    self.pyguppy_load_settings(
  File "/Nanopore/megalodon/megalodon/backends.py", line 1175, in pyguppy_load_settings
    self.pyguppy_set_model_attributes(
  File "/Nanopore/megalodon/megalodon/backends.py", line 1113, in pyguppy_set_model_attributes
    from remora import model_util
  File "/home/prom/.local/lib/python3.8/site-packages/remora/model_util.py", line 15, in <module>
    from torch import nn
  File "/home/prom/.local/lib/python3.8/site-packages/torch/nn/__init__.py", line 1, in <module>
    from .modules import *  # noqa: F403
  File "/home/prom/.local/lib/python3.8/site-packages/torch/nn/modules/__init__.py", line 1, in <module>
    from .module import Module
  File "/home/prom/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 7, in <module>
    from ..parameter import Parameter
  File "/home/prom/.local/lib/python3.8/site-packages/torch/nn/parameter.py", line 2, in <module>
    from torch._C import _disabled_torch_function_impl
ModuleNotFoundError: No module named 'torch._C'
```
I have looked for this error on pytorch github but it I am not sure answers fit my issue.

Any help is appreciated as always !

Best,
Paul

**Comment by marcus1487** [comment]
This does look like an issue with the torch install. Unfortunately I can't provide much feedback on the possibilities for the source of this error. I would note that megalodon is being deprecated and the Remora models are ported into bontio, guppy and dorado. Thus I would recommend using these tools to obtain Remora modified base results.
