### ISSUE TITLE
direct download links ? 

### ISSUE THREAD

**Issue by colindaven** [nanoporetech/remora#47]
Hi,

I'd like to download the remora models directly via wget etc (likely having proxy problems). 
Do you have direct links somewhere ? Thanks

```
remora model download --pore dna_r9.4.1_e8

Traceback (most recent call last):
  File "/home/hpc/davenpor/.local/bin/remora", line 8, in <module>
    sys.exit(run())
  File "/home/hpc/davenpor/.local/lib/python3.7/site-packages/remora/main.py", line 69, in run
    cmd_func(args)
  File "/home/hpc/davenpor/.local/lib/python3.7/site-packages/remora/parsers.py", line 809, in run_download
    model_dl.download(model_url)
  File "/home/hpc/davenpor/.local/lib/python3.7/site-packages/remora/download.py", line 29, in download
    'filename="([^"]+)', req.headers["content-disposition"]
  File "/home/hpc/davenpor/.local/lib/python3.7/site-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-disposition'
```

**Comment by marcus1487** [comment]
I'm not sure why this is happening and will look into this issue, but the direct link can be accessed via `https://nanoporetech.box.com/shared/static/[hash].pt`. The download logic can be found [here in the code](https://github.com/nanoporetech/remora/blob/master/src/remora/download.py).

**Comment by colindaven** [comment]
Thanks, its possibly because our proxy is blocking this site, so please don't waste too much time on it.

```
wget https://nanoporetech.box.com/shared/static/*


Proxy request sent, awaiting response... 403 URLBlocked
2022-12-22 16:31:47 ERROR 403: URLBlocked.

```
