### ISSUE TITLE
Remora modified base  pre-trained model won't download

### ISSUE THREAD

**Issue by ellieanderson** [nanoporetech/remora#51]
Hi, I'm not sure if this should be a remora or megalodon issue. I'm using megalodon in a singularity image and have run into an error message with the following code:

`megalodon \`
    `$FAST5DIR \`
    `--guppy-params "-d /opt/ont/guppy/data" \`
    `--guppy-config dna_r9.4.1_450bps_fast.cfg \`
    `--remora-modified-bases dna_r9.4.1_e8 fast 3.5.1 5mc CG 0 \`
    `--guppy-server-path /usr/bin/guppy_basecall_server \`
    `--guppy-concurrent-reads 4 \`
    `--guppy-timeout 300 \`
    `--outputs basecalls mappings mod_mappings mods \`
    `--reference $S288CFNA \`
    `--output-directory $RESULTS \`
    `--overwrite \`
    `--processes 4 \`
    `--num-reads 10`

```
[09:10:50] Running Megalodon version 2.5.0
******************** WARNING: "mods" output requested, so "per_read_mods" will be added to outputs. ********************
[09:10:50] Loading guppy basecalling backend
******************** WARNING [09:10:52:MainProcess:MainThread:model_util.py:491]: Remora model for basecall model version (3.5.1) not found. Using default Remora model for dna_r9.4.1_e8_fast. ********************
******************** WARNING: Remora model for basecall model version (3.5.1) not found. Using default Remora model for dna_r9.4.1_e8_fast. ********************
[09:10:52] No pre-trained Remora model found for this configuration dna_r9.4.1_e8_fast_v3.5.1_5mc_CG_v0.pt at /usr/local/lib/python3.8/dist-packages/remora/trained_models.
Attempting to download dna_r9.4.1_e8_fast_v3.5.1_5mc_CG_v0.pt
[09:10:52] No pre-trained Remora model found for this configuration dna_r9.4.1_e8_fast_v3.5.1_5mc_CG_v0.pt at /usr/local/lib/python3.8/dist-packages/remora/trained_models.
Attempting to download dna_r9.4.1_e8_fast_v3.5.1_5mc_CG_v0.pt
Traceback (most recent call last):                                                                  
  File "/usr/local/bin/megalodon", line 8, in <module>
    sys.exit(_main())
  File "/usr/local/lib/python3.8/dist-packages/megalodon/__main__.py", line 754, in _main
    megalodon._main(args)
  File "/usr/local/lib/python3.8/dist-packages/megalodon/megalodon.py", line 1797, in _main
    model_info = backends.ModelInfo(
  File "/usr/local/lib/python3.8/dist-packages/megalodon/backends.py", line 596, in __init__
    self.pyguppy_load_settings(
  File "/usr/local/lib/python3.8/dist-packages/megalodon/backends.py", line 1175, in pyguppy_load_settings
    self.pyguppy_set_model_attributes(
  File "/usr/local/lib/python3.8/dist-packages/megalodon/backends.py", line 1126, in pyguppy_set_model_attributes
    _, remora_metadata = model_util.load_model(
  File "/usr/local/lib/python3.8/dist-packages/remora/model_util.py", line 544, in load_model
    md.download(url)
  File "/usr/local/lib/python3.8/dist-packages/remora/download.py", line 44, in download
    with open(self.location(f_name), "wb") as f:
OSError: [Errno 30] Read-only file system: '/usr/local/lib/python3.8/dist-packages/remora/trained_models/dna_r9.4.1_e8_fast_v3.5.1_5mc_CG_v0.pt'
```

I've looked at the remora repo and tried downloading the models outside of megalodon, but get a similar error:

`remora model download --pore dna_r9.4.1_e8 --basecall-model-type fast` 

```
0%|                                                                  | 0.00/1.17M [00:00<?, ?i 
                                                                                               Traceback (most recent call last):
  File "/usr/local/bin/remora", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.8/dist-packages/remora/main.py", line 69, in run
    cmd_func(args)
  File "/usr/local/lib/python3.8/dist-packages/remora/parsers.py", line 809, in run_download
    model_dl.download(model_url)
  File "/usr/local/lib/python3.8/dist-packages/remora/download.py", line 44, in download
    with open(self.location(f_name), "wb") as f:
OSError: [Errno 30] Read-only file system: ‘/usr/local/lib/python3.8/dist-packages/remora/trained_models/dna_r9.4.1_e8_sup_v3.5.1_5mc_CG_v0.pt’ 
```

I have also tried downloading the model directly into the image while building it, but when I ran megalodon, I still got the same error. Any suggestions?

log.txt
```
[09:10:50] Running Megalodon version 2.5.0
DBG 09:10:50 : Command: """/usr/local/bin/megalodon /work/eaa50/met_epi/raw_data/scer_mesmlr/NEG_basecalled_fast5 --guppy-params -d /opt/ont/guppy/data --guppy-config dna_r9.4.1_450bps_fast.cfg --remora-modified-bases dna_r9.4.1_e8 fast 3.5.1 5mc CG 0 --guppy-server-path /usr/bin/guppy_basecall_server --guppy-concurrent-reads 4 --guppy-timeout 300 --outputs basecalls mappings mod_mappings mods --reference /work/eaa50/met_epi/genomes/GCF_000146045.2_R64_genomic.fna.gz --output-directory /work/eaa50/met_epi/results --overwrite --processes 4 --num-reads 10""" --- MainProcess-MainThread megalodon.py:1787
******************** WARNING: "mods" output requested, so "per_read_mods" will be added to outputs. ********************
[09:10:50] Loading guppy basecalling backend
DBG 09:10:50 : Guppy version: "6.4.2" --- MainProcess-MainThread backends.py:938
DBG 09:10:50 : Pyguppy version: "6.4.2" --- MainProcess-MainThread backends.py:939
DBG 09:10:50 : guppy server init command: "/usr/bin/guppy_basecall_server -p auto -l /work/eaa50/met_epi/results/guppy_log -c dna_r9.4.1_450bps_fast.cfg --quiet -d /opt/ont/guppy/data" --- MainProcess-MainThread backends.py:1016
DBG 09:10:50 : Found guppy log file: /work/eaa50/met_epi/results/guppy_log/guppy_basecall_server_log-2023-01-24_09-10-50.log --- MainProcess-MainThread backends.py:1032
DBG 09:10:51 : Guppy server started on port ipc:///tmp/aec7-191e-3dbf-5feb --- MainProcess-MainThread backends.py:973
DBG 09:10:51 : Connecting to server --- MainProcess-MainThread backends.py:872
DBG 09:10:51 : pyguppy server status: result.success --- MainProcess-MainThread backends.py:909
DBG 09:10:51 : Could not load guppy server configuration state: 'Configurations' --- MainProcess-MainThread backends.py:913
DBG 09:10:51 : init_test_read BasecallingCompleted --- MainProcess-MainThread backends.py:1256
DBG 09:10:52 : Loading Remora model from specs: ['dna_r9.4.1_e8', 'fast', '3.5.1', '5mc', 'CG', '0'] --- MainProcess-MainThread backends.py:1123
******************** WARNING: Remora model for basecall model version (3.5.1) not found. Using default Remora model for dna_r9.4.1_e8_fast. ********************
[09:10:52] No pre-trained Remora model found for this configuration dna_r9.4.1_e8_fast_v3.5.1_5mc_CG_v0.pt at /usr/local/lib/python3.8/dist-packages/remora/trained_models.
Attempting to download dna_r9.4.1_e8_fast_v3.5.1_5mc_CG_v0.pt
DBG 09:10:52 : Starting new HTTPS connection (%d): %s:%s --- MainProcess-MainThread connectionpool.py:1003
DBG 09:10:52 : %s://%s:%s "%s %s %s" %s %s --- MainProcess-MainThread connectionpool.py:456
DBG 09:10:52 : %s://%s:%s "%s %s %s" %s %s --- MainProcess-MainThread connectionpool.py:456
DBG 09:10:52 : Starting new HTTPS connection (%d): %s:%s --- MainProcess-MainThread connectionpool.py:1003
DBG 09:10:53 : %s://%s:%s "%s %s %s" %s %s --- MainProcess-MainThread connectionpool.py:456
DBG 09:10:53 : Starting new HTTPS connection (%d): %s:%s --- MainProcess-MainThread connectionpool.py:1003
DBG 09:10:54 : %s://%s:%s "%s %s %s" %s %s --- MainProcess-MainThread connectionpool.py:456
```

**Comment by marcus1487** [comment]
Megalodon is deprecated. I would highly recommend using dorado for the latest modified base basecalling.

The model needs to be downloaded, so the download while running does not seem to be a feasible option. In the last attempt it does not appear as though the model was downlaoded and so the download is attempted and the read-only filesystem issue appears again. I would recommend downloading the model and directly adding it to your container and specifying the model path instead of relying on the automatic download for this use case.

**Comment by ellieanderson** [comment]
Okay, I will definitely look into dorado.

I've tried downloading the model to the container, but am not quite sure how to reference the path. Can I reference it using the `remora-modified-bases` parameter, or would I put it somewhere else?

**Comment by ellieanderson** [comment]
@marcus1487 I've tried directly downloading the remora model (I think) using the following code:
`remora model download --pore dna_r9.4.1_e8 --basecall-model-type fast --basecall-model-version v3.5.1 --modified-bases 5mc  --remora-model-type CG`
but it's still giving me the same errors. Is there another way to download the model?

Error:
```
Traceback (most recent call last):                                                                  
  File "/usr/local/bin/remora", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.8/dist-packages/remora/main.py", line 69, in run
    cmd_func(args)
  File "/usr/local/lib/python3.8/dist-packages/remora/parsers.py", line 809, in run_download
    model_dl.download(model_url)
  File "/usr/local/lib/python3.8/dist-packages/remora/download.py", line 44, in download
    with open(self.location(f_name), "wb") as f:
OSError: [Errno 30] Read-only file system: '/usr/local/lib/python3.8/dist-packages/remora/trained_models/dna_r9.4.1_e8_fast_v3.5.1_5mc_CG_v0.pt'
```

**Comment by marcus1487** [comment]
This is an issue with the file system. Any command you try to run to download a file to a read only file system will fail. Can you run this command on a file system *with* write access and then send the file to your read only file system for input to your remora commands? Saved models will be in this directory of the repository: https://github.com/nanoporetech/remora/tree/master/src/remora/trained_models

**Comment by ellieanderson** [comment]
Ah gotcha. I downloaded it outside of the file system and it ran fine. Manually moving it into the container also worked. Thank you!
