### ISSUE TITLE
Found no BAM records in dataset preparation

### ISSUE THREAD

**Issue by xph9876** [nanoporetech/remora#53]
Hi Remora team, 
I plan to train a new model for modification detection using __remora v2.0.0__. For dataset preparation, I used __dorado v0.1.1__ to generate a bam file
```bash
dorado basecaller ../models_dorado/dna_r9.4.1_e8_sup@v3.3 pod5s/ | samtools view -b > bam/covid_one_file.bam
```
Then I use this dataset to do a dataset preparation
```bash
remora dataset prepare pod5s_one/output.pod5 bam/covid_one_file.bam --mod-base-control
```
However, there is an error message indicating that __there is no BAM records__:
```
Indexing BAM by read id: 0 Reads [00:00, ? Reads/s]
[21:48:35] Found 0 BAM records and 52649 POD5 reads
[21:48:35] Making reference-anchored training data
[21:48:35] Allocating memory for output tensors
Traceback (most recent call last):
  File "/storage/home/hcoda1/0/pxu64/.conda/envs/dorado/bin/remora", line 8, in <module>
    sys.exit(run())
  File "/storage/home/hcoda1/0/pxu64/.conda/envs/dorado/lib/python3.10/site-packages/remora/main.py", line 69, in run
    cmd_func(args)
  File "/storage/home/hcoda1/0/pxu64/.conda/envs/dorado/lib/python3.10/site-packages/remora/parsers.py", line 275, in run_dataset_prepare
    extract_chunk_dataset(
  File "/storage/home/hcoda1/0/pxu64/.conda/envs/dorado/lib/python3.10/site-packages/remora/prepare_train_data.py", line 196, in extract_chunk_dataset
    assert len(bam_idx.keys()) > 0
AssertionError
```
I checked the bam file and found it is not empty. I also converted it to the SAM file, here are some sample lines:
```
01624d83-01c2-4150-8cfa-bc03c65578d3    4       *       0       0       *    *0       378     CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCGAGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGAGAGAGAGAGAGAGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGAGAGAGAGAGAGAGAGAGAGAGAGAGACCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG    &'=FJI{{{{{{{{{{GHGGGGGHIECCIIHG{{{{JKFCDGIGN{{{{GHDDIH{{{{{{{{{{{{{IEDDFJN{{{{{{FFFGM{{{{{{{{{{{{{{{{{{{{{{{IFDCA??=<:6445443'""""""""##5455688788876322210//000/.--.---*+**+*++,,-,,(,+,&%&&&&())*++,,--------------,,,,,,++++++++)'%&())-000/1/0//02223221422/*('(+-8<@DIJPK{{{{{{JM5+.7AE{JP{{{{{{{{{{{{{{{{{{{{{{LGGHDCA@><:74,))),+-012358:=?BEEIJ{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{LMJ>   qs:i:13  du:f:3.07902    ns:i:9274       ts:i:10 mx:i:4  ch:i:415        st:Z:2017-09-05T15:10:35.232+00:00    rn:i:159        f5:Z:output.pod5        sm:f:110.024  sd:f:21.473     sv:Z:quantile
0205acb5-3493-4f69-ad63-084e3eec2658    4       *       0       0       *    *0       580     CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG      2:>?@BBBAA@=;:;?BECCCBA@@=;;=?@@@?<:88<>?ACFGHIIHHHHIDDDDFIG{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{J{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{HOEBJK{{{{{{{{{{{{{GGGGHGGFFFFFEEFFFFECB@@@@@@@@@@@@@@@?????6*'(+,1347:>?ACDEEFEECA<76654345679:;=?ABABAAAA@A@AACDDDIHHGGG{{{{JGEC@=<:43334567665431/.-,))(((''''&&&&$.00000./.0/1010213356::<<=<=;=<;8::<;=;><><=;;9;;>=45.*&',+-.1146;?AAA>8445@ABDEJGG{{{{LFFGGFGFO{{{{{{{{{{{{{{{{{{{{{{{{{IGHHEB?=<:863,%%%%%&&&(/11234457889:;<=>?@AAAAA@>=;::987654345567:<=>>>???@@@????>=<;985321.)%%%$    qs:i:17 du:f:4.61952    ns:i:13914      ts:i:10 mx:i:4  ch:i:417      st:Z:2017-09-05T15:10:39.832+00:00      rn:i:386        f5:Z:output.pod5      sm:f:113.098    sd:f:21.993     sv:Z:quantile
038eb305-30b6-49d6-997f-1b548795164e    4       *       0       0       *    *0       424     CACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACAACACACACACACACACACACACACACACACAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACAGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG      %'))*)))''''&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&'*+..0123557898::;;<<<<==>=>>>>>========<=;<;<;;::;<<<<<<=<=====<<;;;;;;;<;;;;;::;;<<<<;::9989999::;;;;;:::<;<<=<<;;;;;;;:;;;;;;;<<<<=<=<<;;:::::888888899::;9:78564646577;:;:2.*++,,00223355555555555555330.*'&&'(*,4456679;:<<?=?<=::787:9;:<:;:;9:89787878776766543220,***))))'$$$--/123333210..-,*)'%###########""###$&'&'()-245679;<<9630/-./.,*)((*(%&'    qs:i:10 du:f:4.17596    ns:i:12578      ts:i:10 mx:i:3  ch:i:405      st:Z:2017-09-05T15:08:14.238+00:00      rn:i:77 f5:Z:output.pod5     sm:f:120.602     sd:f:27.862     sv:Z:quantile
```
Do you have any opinion how should I solve the error?

**Comment by marcus1487** [comment]
Remora also requires mapped reads to extract the reference sequence for training (with the MD tag). Training from basecaller sequence is not currently supported (but possible via the API)

**Comment by xph9876** [comment]
Thank you for the quick response, marcus! Should I generate the unaligned bam using dorado and then align them to generate the mapped reads? Also, how do I add the log file?

**Comment by marcus1487** [comment]
Yes. Use the samtools fastq `-T "*"` option to carry the tags over and the minimap2 `-y` flag to copy the tags into the output aligned bam file. 

I'm not at a terminal, but all remora commands accept the `-h` flag to see all options. The exact log file option will be here.

**Comment by xph9876** [comment]
Thank you, marcus! The issue is solved! As a summary, here are the command I used to create a dataset using dorado :)
```bash
# basecalling to unaligned bam
dorado basecaller ../models_dorado/dna_r9.4.1_e8_sup@v3.3 pod5s/ --emit_moves| samtools view -b > bam/covid.bam
# convert to fastq with original tags
samtools fastq covid.bam -T '*' > covid.fq
# align using minimap2
minimap2 ref.mmi covid.fq --MD -y > covid_aligned.bam
# create dataset
remora dataset prepare pod5s/covid.pod5 covid_aligned.bam --mod-base-control --output-remora-training-file covid.npz --log-filename covid_dataset.log
```
