### ISSUE TITLE
Bonito unable to read modified base remora torch models

### ISSUE THREAD

**Issue by jorisbalc** [nanoporetech/remora#59]
Hi,
I'm trying to use a trained model with bonito with the following command:

```
bonito basecaller --modified-base-model train_results/model_best.pt dna_r10.4.1_e8.2_400bps_hac@v3.5.2 --device cuda:0 BC5/ > output.bam

```
However I cannot seem to wrap my head around this error:
```
> reading pod5
> outputting unaligned bam
> loading model dna_r10.4.1_e8.2_400bps_hac@v3.5.2
> loading modified base model
Traceback (most recent call last):
  File "/home/v313/.local/bin/bonito", line 8, in <module>
    sys.exit(main())
  File "/home/v313/.local/lib/python3.8/site-packages/bonito/__init__.py", line 34, in main
    args.func(args)
  File "/home/v313/.local/lib/python3.8/site-packages/bonito/cli/basecaller.py", line 75, in main
    mods_model = load_mods_model(
  File "/home/v313/.local/lib/python3.8/site-packages/bonito/mod_util.py", line 55, in load_mods_model
    return load_model(model_path, quiet=True, device=device)
  File "/home/v313/.local/lib/python3.8/site-packages/remora/model_util.py", line 499, in load_model
    return load_onnx_model(model_filename, device, quiet=quiet)
  File "/home/v313/.local/lib/python3.8/site-packages/remora/model_util.py", line 350, in load_onnx_model
    model_sess = ort.InferenceSession(
  File "/home/v313/.local/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 347, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/v313/.local/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 384, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from train_results/model_best.pt failed:Protobuf parsing failed.
```
I've seen similar issues posted on bonito's repo with rerio models, however there was no apparent solution. Is this a result of the torchscript format not working and should I look into converting the model to the onnx format? Thanks in advance.

**Comment by marcus1487** [comment]
The remora upgrade has not been pushed to a new bonito version on pypi. As a workaround you can install bonito from github `pip install git+https://github.com/nanoporetech/bonito` and remora torch model should work.

**Comment by jorisbalc** [comment]
The error still persists after reinstalling bonito with the mentioned command. I must mention that I have torch 1.12.1+cu113 installed manually to overcome the compatibility issues with ampere GPUs for bonito. I have also tried 1.11.0+cu113 torch version, but I get the same error.

**Comment by marcus1487** [comment]
Remora 2.0 (required for latest bonito installation) no longer supports onnx format models. It seems that you have somehow linked to an older remora version. Did your new installation of bonito complete without error? Could you provide the installation output?

**Comment by jorisbalc** [comment]
```
pip uninstall ont-bonito
```
Afterwards I install it using the command line provided:
```
pip install git+https://github.com/nanoporetech/bonito
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/nanoporetech/bonito
  Cloning https://github.com/nanoporetech/bonito to /tmp/pip-req-build-o8r851j_
  Running command git clone --filter=blob:none --quiet https://github.com/nanoporetech/bonito /tmp/pip-req-build-o8r851j_
  Resolved https://github.com/nanoporetech/bonito to commit 23820924eee16d4a07691c97b27ff71b7462d38f
  Preparing metadata (setup.py) ... done
Requirement already satisfied: fast-ctc-decode==0.3.2 in ./.local/lib/python3.8/site-packages (from ont-bonito==0.6.2) (0.3.2)
Requirement already satisfied: mappy==2.24 in ./.local/lib/python3.8/site-packages (from ont-bonito==0.6.2) (2.24)
Requirement already satisfied: numpy~=1.21.5 in ./.local/lib/python3.8/site-packages (from ont-bonito==0.6.2) (1.21.6)
Requirement already satisfied: onnxruntime==1.12.1 in ./.local/lib/python3.8/site-packages (from ont-bonito==0.6.2) (1.12.1)
Requirement already satisfied: ont-fast5-api==3.3.0 in ./.local/lib/python3.8/site-packages (from ont-bonito==0.6.2) (3.3.0)
Requirement already satisfied: ont-koi==0.1.4 in ./.local/lib/python3.8/site-packages (from ont-bonito==0.6.2) (0.1.4)
Requirement already satisfied: ont-remora==2.0.0 in ./.local/lib/python3.8/site-packages (from ont-bonito==0.6.2) (2.0.0)
Requirement already satisfied: pandas<2,>1 in ./.local/lib/python3.8/site-packages (from ont-bonito==0.6.2) (1.4.3)
Requirement already satisfied: parasail==1.2 in ./.local/lib/python3.8/site-packages (from ont-bonito==0.6.2) (1.2)
Requirement already satisfied: pod5==0.1.0 in ./.local/lib/python3.8/site-packages (from ont-bonito==0.6.2) (0.1)
Requirement already satisfied: pysam==0.20.0 in ./.local/lib/python3.8/site-packages (from ont-bonito==0.6.2) (0.20.0)
Requirement already satisfied: python-dateutil==2.8.2 in ./.local/lib/python3.8/site-packages (from ont-bonito==0.6.2) (2.8.2)
Requirement already satisfied: requests==2.25.1 in ./.local/lib/python3.8/site-packages (from ont-bonito==0.6.2) (2.25.1)
Requirement already satisfied: scipy==1.7.3 in ./.local/lib/python3.8/site-packages (from ont-bonito==0.6.2) (1.7.3)
Requirement already satisfied: toml==0.10.2 in ./.local/lib/python3.8/site-packages (from ont-bonito==0.6.2) (0.10.2)
Requirement already satisfied: torch~=1.12.1 in ./.local/lib/python3.8/site-packages (from ont-bonito==0.6.2) (1.12.1+cu113)
Requirement already satisfied: tqdm<5,>4 in ./.local/lib/python3.8/site-packages (from ont-bonito==0.6.2) (4.64.0)
Requirement already satisfied: packaging in ./.local/lib/python3.8/site-packages (from onnxruntime==1.12.1->ont-bonito==0.6.2) (21.3)
Requirement already satisfied: protobuf in ./.local/lib/python3.8/site-packages (from onnxruntime==1.12.1->ont-bonito==0.6.2) (3.20.1)
Requirement already satisfied: flatbuffers in ./.local/lib/python3.8/site-packages (from onnxruntime==1.12.1->ont-bonito==0.6.2) (2.0)
Requirement already satisfied: sympy in ./.local/lib/python3.8/site-packages (from onnxruntime==1.12.1->ont-bonito==0.6.2) (1.10.1)
Requirement already satisfied: coloredlogs in ./.local/lib/python3.8/site-packages (from onnxruntime==1.12.1->ont-bonito==0.6.2) (15.0.1)
Requirement already satisfied: progressbar33>=2.3.1 in ./.local/lib/python3.8/site-packages (from ont-fast5-api==3.3.0->ont-bonito==0.6.2) (2.4)
Requirement already satisfied: h5py>=2.8 in ./.local/lib/python3.8/site-packages (from ont-fast5-api==3.3.0->ont-bonito==0.6.2) (3.7.0)
Requirement already satisfied: cffi in ./.local/lib/python3.8/site-packages (from ont-koi==0.1.4->ont-bonito==0.6.2) (1.15.1)
Requirement already satisfied: tabulate in ./.local/lib/python3.8/site-packages (from ont-remora==2.0.0->ont-bonito==0.6.2) (0.8.10)
Requirement already satisfied: thop in ./.local/lib/python3.8/site-packages (from ont-remora==2.0.0->ont-bonito==0.6.2) (0.1.1.post2207130030)
Requirement already satisfied: scikit-learn in ./.local/lib/python3.8/site-packages (from ont-remora==2.0.0->ont-bonito==0.6.2) (1.1.2)
Requirement already satisfied: wheel in /usr/lib/python3/dist-packages (from parasail==1.2->ont-bonito==0.6.2) (0.34.2)
Requirement already satisfied: pyarrow~=8.0.0 in ./.local/lib/python3.8/site-packages (from pod5==0.1.0->ont-bonito==0.6.2) (8.0.0)
Requirement already satisfied: vbz-h5py-plugin in ./.local/lib/python3.8/site-packages (from pod5==0.1.0->ont-bonito==0.6.2) (1.0.1)
Requirement already satisfied: iso8601 in ./.local/lib/python3.8/site-packages (from pod5==0.1.0->ont-bonito==0.6.2) (1.1.0)
Requirement already satisfied: pytz in ./.local/lib/python3.8/site-packages (from pod5==0.1.0->ont-bonito==0.6.2) (2022.1)
Requirement already satisfied: jsonschema in ./.local/lib/python3.8/site-packages (from pod5==0.1.0->ont-bonito==0.6.2) (4.17.3)
Requirement already satisfied: more-itertools in ./.local/lib/python3.8/site-packages (from pod5==0.1.0->ont-bonito==0.6.2) (9.0.0)
Requirement already satisfied: lib-pod5~=0.1 in ./.local/lib/python3.8/site-packages (from pod5==0.1.0->ont-bonito==0.6.2) (0.1.5)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil==2.8.2->ont-bonito==0.6.2) (1.14.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3/dist-packages (from requests==2.25.1->ont-bonito==0.6.2) (1.25.8)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests==2.25.1->ont-bonito==0.6.2) (2019.11.28)
Requirement already satisfied: idna<3,>=2.5 in /usr/lib/python3/dist-packages (from requests==2.25.1->ont-bonito==0.6.2) (2.8)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/lib/python3/dist-packages (from requests==2.25.1->ont-bonito==0.6.2) (3.0.4)
Requirement already satisfied: typing-extensions in ./.local/lib/python3.8/site-packages (from torch~=1.12.1->ont-bonito==0.6.2) (4.3.0)
Requirement already satisfied: pycparser in ./.local/lib/python3.8/site-packages (from cffi->ont-koi==0.1.4->ont-bonito==0.6.2) (2.21)
Requirement already satisfied: humanfriendly>=9.1 in ./.local/lib/python3.8/site-packages (from coloredlogs->onnxruntime==1.12.1->ont-bonito==0.6.2) (10.0)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in ./.local/lib/python3.8/site-packages (from jsonschema->pod5==0.1.0->ont-bonito==0.6.2) (0.19.3)
Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python3.8/dist-packages (from jsonschema->pod5==0.1.0->ont-bonito==0.6.2) (22.1.0)
Requirement already satisfied: pkgutil-resolve-name>=1.3.10 in ./.local/lib/python3.8/site-packages (from jsonschema->pod5==0.1.0->ont-bonito==0.6.2) (1.3.10)
Requirement already satisfied: importlib-resources>=1.4.0 in ./.local/lib/python3.8/site-packages (from jsonschema->pod5==0.1.0->ont-bonito==0.6.2) (5.10.2)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in ./.local/lib/python3.8/site-packages (from packaging->onnxruntime==1.12.1->ont-bonito==0.6.2) (3.0.9)
Requirement already satisfied: threadpoolctl>=2.0.0 in ./.local/lib/python3.8/site-packages (from scikit-learn->ont-remora==2.0.0->ont-bonito==0.6.2) (3.1.0)
Requirement already satisfied: joblib>=1.0.0 in ./.local/lib/python3.8/site-packages (from scikit-learn->ont-remora==2.0.0->ont-bonito==0.6.2) (1.1.0)
Requirement already satisfied: mpmath>=0.19 in ./.local/lib/python3.8/site-packages (from sympy->onnxruntime==1.12.1->ont-bonito==0.6.2) (1.2.1)
Requirement already satisfied: zipp>=3.1.0 in /usr/local/lib/python3.8/dist-packages (from importlib-resources>=1.4.0->jsonschema->pod5==0.1.0->ont-bonito==0.6.2) (3.8.1)
Building wheels for collected packages: ont-bonito
  Building wheel for ont-bonito (setup.py) ... done
  Created wheel for ont-bonito: filename=ont_bonito-0.6.2-py3-none-any.whl size=61093 sha256=404731169391be5c2beaed3e05067df341cda589c2dd72b38267c96f7f9c341c
  Stored in directory: /tmp/pip-ephem-wheel-cache-4usjodql/wheels/33/14/15/3ff620ea4f0676715d26d791f1c141018a11395832dbe7cf2e
Successfully built ont-bonito
Installing collected packages: ont-bonito
Successfully installed ont-bonito-0.6.2
```

**Comment by marcus1487** [comment]
It does appear as though you are installing the correct remora version, but at run time you are accessing an older remora version. This is likely a python environment issue. I would recommend create a fresh virtual environment `python -m venv venv` and install bonito within this to avoid any conflicts with other remora installations.
