### ISSUE TITLE
novel modifications 

### ISSUE THREAD

**Issue by Taojianchang** [nanoporetech/remora#97]
Hello,

We try to train a remora model for a modification of A to Z base. Canonical and modified bam were generated by bonito using reference genome sequence. 
bonito basecaller dna_r10.4.1_e8.2_400bps_sup@v3.5.2 --reference p15-0168.mmi 0704LA23002-016_P15-0168-Z_151Z > z_150Z_basecalls_400_aligned.bam

The workflow using remora is as follows:
remora \
  dataset prepare \
  cm_150Z_merged.pod5 \
  cm_150Z_basecalls_400_aligned.bam \
  --output-remora-training-file can_chunks.npz \
  --log-filename prep_can.log \
  --refine-kmer-level-table kmer_models/dna_r10.4.1_e8.2_400bps/9mer_levels_v1.txt  \
  --refine-rough-rescale \
  --mod-base-control
  
remora \
  dataset prepare \
  z_150Z_merged.pod5 \
  z_150Z_basecalls_400_aligned.bam \
  --output-remora-training-file mod_chunks.npz \
  --log-filename prep_can.log \
  --refine-kmer-level-table kmer_models/dna_r10.4.1_e8.2_400bps/9mer_levels_v1.txt \
  --refine-rough-rescale \
  --mod-base A NewMod
 
...

remora \
  validate from_modbams \
  --bam-and-bed can_infer.bam can_gt.bed \
  --bam-and-bed mod_infer.bam mod_gt.bed \
  --full-results-filename validation_results.txt

The can_gt.bed and mod_gt.bed were generated by modkit
modkit motif-bed p15-0168.fa A 0 > tmp
awk 'BEGIN{OFS="\t"} {$4="A"; print}' tmp > can_gt.bed
cp can_gt.bed mod_gt.bed

I am not sure the bed file generated in a correct way and the whole workflow is reasonable. It raise error in last step (see as follows). Could you give me some advices ?

Traceback (most recent call last):
  File "/home/jianchang/software/miniconda3/envs/remora/bin/remora", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/home/jianchang/software/miniconda3/envs/remora/lib/python3.11/site-packages/remora/main.py", line 71, in run
    cmd_func(args)
  File "/home/jianchang/software/miniconda3/envs/remora/lib/python3.11/site-packages/remora/parsers.py", line 1276, in run_validate_modbams
    validate_modbams(
  File "/home/jianchang/software/miniconda3/envs/remora/lib/python3.11/site-packages/remora/validate.py", line 606, in validate_modbams
    probs, labels = parse_mod_bam(
                    ^^^^^^^^^^^^^^
  File "/home/jianchang/software/miniconda3/envs/remora/lib/python3.11/site-packages/remora/validate.py", line 533, in parse_mod_bam
    raise RemoraError(
remora.RemoraError: No valid modification calls from can_infer.bam. Confirm that contig names from reference FASTA and ground truth BED match.

**Comment by marcus1487** [comment]
How was the `can_infer.bam` file produced? Can you load this in a browser and confirm that modified base calls exist and are mapped to the reference?

**Comment by Taojianchang** [comment]
The can_infer.bam was produced by command as follows:
remora \
  dataset merge \
  --input-dataset can_chunks.npz 10_000_000 \
  --input-dataset mod_chunks.npz 10_000_000 \
  --output-dataset chunks.npz
  
remora \
  model train \
  chunks.npz \
  --model /home/jianchang/software/remora/models/ConvLSTM_w_ref.py \
  --device 0 \
  --output-path train_results
  
remora \
  infer from_pod5_and_bam \
  cm_150Z_merged.pod5 \
  cm_150Z_basecalls_400_aligned.bam \
  --model train_results/model_best.pt \
  --out-bam can_infer.bam \
  --device 0

remora \
  infer from_pod5_and_bam \
  z_150Z_merged.pod5 \
  z_150Z_basecalls_400_aligned.bam \
  --model train_results/model_best.pt \
  --out-bam mod_infer.bam \
  --device 0

The can_infer.bam and mod_infer.bam were screened using samtools. The reference genome sequence p15-0168-cm- is mapped, however the modified base position is unknown. 

can_infer.bam
<img width="1021" alt="截屏2023-07-25 12 55 30" src="https://github.com/nanoporetech/remora/assets/50445680/911368a4-8b3d-4fe0-be2e-55218c1a26fe">

mod_infer.bam
<img width="1012" alt="image" src="https://github.com/nanoporetech/remora/assets/50445680/66f88dd4-4bbf-419c-a03d-13de0e47d31d">

**Comment by marcus1487** [comment]
Have you confirmed in a genome browser that the provided BED file does indeed overlap the correct positions? The other thing to try here would be to upgrade pysam. I know older versions would not parse the modified base tags correctly. I would also suggest adding the log file as this may point to the issue.

**Comment by marcus1487** [comment]
Any updates on this issue? Or has this been resolved?

**Comment by marcus1487** [comment]
Closing due to inactivity.
